<!DOCTYPE html>
<html>
<head>
    <title>All Orders Report</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 12px; color: #333; }
        header { text-align: center; margin-bottom: 20px; }
        header img { max-height: 80px; }
        h1 { font-size: 18px; margin: 5px 0; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        table, th, td { border: 1px solid #ccc; }
        th, td { padding: 8px; text-align: left; }
        th { background-color: #f5f5f5; }
        footer { text-align: center; font-size: 10px; color: #666; margin-top: 20px; }
    </style>
</head>
<body>

<header>
    <img src="{{ public_path('images/logo.png') }}" alt="Logo Restoran">
    <h1>Seribu Rasa Laundry</h1>
    <p>Jl. Menteng Jaya No.18, Jakarta Pusat</p>
    <h3>All Orders Report</h3>
</header>

<table>
    <thead>
        <tr>
            <th>No</th>
            <th>Order Code</th>
            <th>Customer</th>
            <th>Phone</th>
            <th>Address</th>
            <th>Order Date</th>
            <th>End Date</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>
        @foreach($orders as $key => $item)
        <tr>
            <td>{{ $key + 1 }}</td>
            <td>{{ $item->order_code }}</td>
            <td>{{ $item->customer->customer_name ?? '-' }}</td>
            <td>{{ $item->customer->phone ?? '-' }}</td>
            <td>{{ $item->customer->address ?? '-' }}</td>
            <td>{{ $item->order_date }}</td>
            <td>{{ $item->order_end_date }}</td>
            <td>{{ $item->order_status == 0 ? 'Pending' : 'Pickup' }}</td>
        </tr>
        @endforeach
    </tbody>
</table>

<footer>
    Generated by Seribu Rasa Laundry System - {{ date('d-m-Y H:i') }}
</footer>

</body>
</html>
